scan_planner_node:
  ros__parameters:
    fsm.navi_mode: 2
    fsm.waypoints:
    - -7.2
    - 0.0
    - 4.70
    - -9.0
    - 0.0
    - 4.70
    - -9.0
    - -2.6
    - 4.70
    - -9.5
    - -6.5
    - 4.70
    - -8.2
    - -6.5
    - 4.70
    - -7.0
    - -6.5
    - 4.70
